### ISSUE TITLE
Can't export frames as PNGs

### ISSUE THREAD

**Issue by ZeWaka** [AnturK/dmiEditor#2]
title, can't export icons/frames as pngs back to an editor

https://user-images.githubusercontent.com/4741640/167699454-9c9b15ab-3c64-4c2f-834a-be70b5711b48.mp4

**Comment by AnturK** [comment]
Should be partially fixed by dafbe54c63cd1af6f2d6f08c9829a604fc1b7d1e
No support for pasting multiple frames as of now.
