### ISSUE TITLE
Feature Request: Selection Indicator for iconstate frames

### ISSUE THREAD

**Issue by ZeWaka** [AnturK/dmiEditor#5]
Currently, you can click an animation frame to select it and copy/cut/paste and stuff, but there's no indication that you've actually selected said frame, unlike with selection of iconstates.

e.g, guess which of these is selected:
![image](https://user-images.githubusercontent.com/4741640/169630119-668ec0b2-143e-408d-9650-d2ab4f497ac2.png)

**Comment by AnturK** [comment]
Should be fixed in 1.0.4
